version: '3'
services:
  my-app:
    build:
      context: .
      args:
        STUDENT_NAME: "Nathaniel Ezra Anasbi"
        STUDENT_NIM: "00000068232"
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    command: npm run start
    volumes:
      - .:/app
